/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,ts,jsx,tsx}", "./components/**/*.{js,ts,jsx,tsx}", "./utils/**/*.{js,ts,jsx,tsx}"],
  plugins: [require("daisyui")],
  darkTheme: "dark",
  darkMode: ["selector", "[data-theme='dark']"],
  daisyui: {
    themes: [
      {
        light: {
          primary: "#ff3c1f",
          "primary-content": "#ffffff",
          secondary: "#26313b",
          "secondary-content": "#ffffff",
          accent: "#4e5860",
          "accent-content": "#ffffff",
          neutral: "#a6abaf",
          "neutral-content": "#26313b",
          "base-100": "#ffffff",
          "base-200": "#d9e0e2",
          "base-300": "#a6abaf",
          "base-content": "#26313b",
          info: "#3ABFF8",
          success: "#36D399",
          warning: "#FBBD23",
          error: "#F87272",
          "--rounded-btn": "0.5rem",
          ".tooltip": { "--tooltip-tail": "6px" },
          ".link": { textUnderlineOffset: "2px" },
          ".link:hover": { opacity: "80%" },
        },
      },
      {
        dark: {
          primary: "#dd3c1f",
          "primary-content": "#1C2129",
          secondary: "#dd3c1f",
          "secondary-content": "#1C2129",
          accent: "#dd3c1f",
          "accent-content": "#1C2129",
          neutral: "#1A1A1A",
          "neutral-content": "#FFFFFF",
          "base-100": "#1C2129",
          "base-200": "#1C2129",
          "base-300": "#1C2129",
          "base-content": "#FFFFFF",
          info: "#3ABFF8",
          success: "#36D399",
          warning: "#FBBD23",
          error: "#F87272",
          "--rounded-btn": "0.5rem",
          ".tooltip": { "--tooltip-tail": "6px", "--tooltip-color": "oklch(var(--p))" },
          ".link": { textUnderlineOffset: "2px" },
          ".link:hover": { opacity: "80%" },
        },
      },
    ],
  },
  theme: {
    extend: {
      boxShadow: { center: "0 0 12px -2px rgb(0 0 0 / 0.05)" },
      animation: { "pulse-fast": "pulse 1s cubic-bezier(0.4, 0, 0.6, 1) infinite" },
    },
  },
};
